networks:
  agenda-network:
     driver: bridge
services:
  agenda-api:
     build:
         context: .  
         dockerfile: Dockerfile
     ports:
         - "8082:8082"
     depends_on:
         - postgres
     networks:
         - agenda-network
  postgres:
     image: postgres:latest
     environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: coti
        POSTGRES_DB: bdagendaapi
     ports:
        - "5435:5432"
     networks:
         - agenda-network



